import 'site_hub_screen.dart';

// Shared card data behind studio/library/arcade, and the pool the random
// generator (see random_screen.dart) draws from. Kept together here so that
// pool always matches what's actually shown on the three hub pages.

const studioCards = [
  SiteCardData(
    title: 'scaler',
    description: 'a tool to help musicians discover what key a song could be in',
    tags: ['music'],
    url: 'https://colleenkhm.github.io/scaler/',
  ),
  SiteCardData(
    title: 'bbc rewind: sound effects',
    description: 'thousands of sound effects for free download',
    tags: ['audio'],
    url: 'https://sound-effects.bbcrewind.co.uk/',
  ),
  SiteCardData(
    title: 'animal sounds',
    description: 'animal sounds, images, and videos',
    tags: ['audio', 'visual', 'animals'],
    url: 'https://search.macaulaylibrary.org/catalog',
  ),
  SiteCardData(
    title: 'tune find',
    description: 'find songs included in tv show episodes',
    tags: ['audio', 'music', 'tv', 'lookup'],
    url: 'https://www.tunefind.com/',
  ),
  SiteCardData(
    title: 'soundhound',
    description: 'find a song by humming',
    tags: ['audio', 'music', 'lookup'],
    url: 'https://music.soundhound.com/soundhound',
  ),
  SiteCardData(
    title: 'supercook',
    description: 'enter the ingredients you have on hand to get recipes with only those ingredients',
    tags: ['cooking', 'recipes'],
    url: 'https://www.supercook.com',
  ),
  SiteCardData(
    title: 'quinapalus',
    description: 'search for words with a particular letter pattern (very robust, super helpful for crosswords)',
    tags: ['words', 'letters', 'lookup'],
    url: 'https://www.quinapalus.com/qat.html',
  ),
  SiteCardData(
    title: 'just a word',
    description: 'a simple resource for looking up words',
    tags: ['words', 'writing'],
    url: 'https://www.just-a-word.com/',
  ),
  SiteCardData(
    title: 'reverse dictionary',
    description: 'a simple resource for looking up words',
    tags: ['words', 'writing'],
    url: 'https://www.onelook.com/thesaurus/',
  ),
  SiteCardData(
    title: 'forvo',
    description: 'look up a word and hear clips of native speakers pronouncing it',
    tags: ['words', 'language'],
    url: 'https://forvo.com/',
  ),
  SiteCardData(
    title: 'youglish',
    description: 'look up a word to hear clips of native speakers pronouncing it in the context of natural speech, with subtitles',
    tags: ['code', 'learning'],
    url: 'https://www.freecodecamp.org/',
  ),
  SiteCardData(
    title: 'nameberry',
    description: 'name search by starting letters, ending letters, number of syllables, etc.',
    tags: ['names', 'writing'],
    url: 'https://nameberry.com/',
  ),
  SiteCardData(
    title: 'freeCodeCamp',
    description: 'a non-profit resource with self-paced coding tutorials that walk you through building real projects',
    tags: ['code', 'learning'],
    url: 'https://www.freecodecamp.org/',
  ),
  SiteCardData(
    title: 'the free dictionary',
    description: 'all words that start or end with a letter or letters',
    tags: ['words'],
    url: 'https://www.thefreedictionary.com/',
  ),
  SiteCardData(
    title: "green's dictionary of slang",
    description: 'slang dictionary for the last 500 years',
    tags: ['words'],
    url: 'https://greensdictofslang.com/',
  ),
  SiteCardData(
    title: "omniglot",
    description: 'encyclopedia of writing systems and languages',
    tags: ['words', 'language'],
    url: 'https://www.omniglot.com/',
  ),
  SiteCardData(
    title: "which book",
    description: 'site that helps you find books you might like via customizable feature sliders',
    tags: ['books', 'choice assist'],
    url: 'https://www.whichbook.net/',
  ),
  SiteCardData(
    title: "what should I read next",
    description: 'suggests books you might like based on books you already like',
    tags: ['books', 'choice assist'],
    url: 'https://www.whatshouldireadnext.com/',
  ),
  SiteCardData(
    title: "understand shakespeare",
    description: 'look up any line from shakespeare and see a list of academic articles that mention it',
    tags: ['shakespeare', 'literature', 'database'],
    url: 'https://www.whatshouldireadnext.com/',
  ),
  SiteCardData(
    title: "power moby dick",
    description: 'line-by-line annotations of moby-dick',
    tags: ['literature'],
    url: 'https://powermobydick.com/',
  ),
  SiteCardData(
    title: "comics devices",
    description: 'reference library of visual narrative devices used in comics',
    tags: ['comics'],
    url: 'https://comicsdevices.com/',
  ),
  SiteCardData(
    title: "universal hint system",
    description: 'database of computer game hints',
    tags: ['games', 'database'],
    url: 'https://www.uhs-hints.com/',
  ),
  SiteCardData(
    title: "marginalia search",
    description: 'serendipitous search engine (favors text-heavy sites/older sites)',
    tags: ['search', 'open source'],
    url: 'https://marginalia-search.com/',
  ),
  SiteCardData(
    title: "stitch picture dictionary",
    description: 'serendipitous search engine (favors text-heavy sites/older sites)',
    tags: ['dictionary', 'art', 'crafts', 'sewing'],
    url: 'https://www.embroidery.rocksea.org/reference/picture-dictionary/',
  ),
  SiteCardData(
    title: "falling fruit",
    description: 'map where people mark fruit trees free for harvesting',
    tags: ['map', 'reference', 'gathering', 'database'],
    url: 'https://fallingfruit.org/map',
  ),
  SiteCardData(
    title: "wildflower search",
    description: 'searchable wildflower database',
    tags: ['search', 'reference', 'gathering', 'database'],
    url: 'https://wildflowersearch.org/search?page=Instructions',
  ),
  SiteCardData(
    title: "TOSDR",
    description: 'grades and summarizes terms of service and privacy policies for websites',
    tags: ['privacy', 'reference'],
    url: 'https://tosdr.org/en',
  ),
  SiteCardData(
    title: "native land maps",
    description: 'map with names of indigenous nations and languages',
    tags: ['language', 'map', 'reference'],
    url: 'https://native-land.ca/maps/native-land',
  ),
  SiteCardData(
    title: "the medieval bestiary",
    description: 'animals of the middle ages',
    tags: ['animals', 'reference'],
    url: 'https://bestiary.ca/',
  ),
  SiteCardData(
    title: "this to that",
    description: 'what glue to use to glue this to that',
    tags: ['craft', 'repair'],
    url: 'https://www.thistothat.com/',
  ),
  SiteCardData(
    title: "this to that",
    description: 'what glue to use to glue this to that',
    tags: ['craft', 'repair'],
    url: 'https://www.thistothat.com/',
  ),
  SiteCardData(
    title: 'coolors',
    description: 'a color palette generator for finding and fine-tuning color schemes',
    tags: ['design', 'color'],
    url: 'https://coolors.co/',
  ),
  SiteCardData(
    title: 'inkarnate',
    description: 'a fantasy map-making tool for building worlds for stories, games, and campaigns',
    tags: ['design', 'worldbuilding'],
    url: 'https://inkarnate.com/',
  ),
  SiteCardData(
    title: 'rooms.xyz',
    description: 'a tool for designing and decorating virtual rooms with real furniture and decor',
    tags: ['design', 'interior'],
    url: 'https://rooms.xyz/',
  ),
  SiteCardData(
    title: 'anime.js',
    description: 'a lightweight JavaScript animation library for building smooth, complex web animations',
    tags: ['code', 'animation'],
    url: 'https://animejs.com/',
  ),
  SiteCardData(
    title: 'bandlab',
    description: 'a free, cloud-based studio for recording, mixing, and collaborating on music online',
    tags: ['music', 'tool'],
    url: 'https://www.bandlab.com',
  ),
  SiteCardData(
    title: 'musicca tuner',
    description: 'a simple online tuner for getting your instrument in tune',
    tags: ['music', 'tool'],
    url: 'https://www.musicca.com/tuner',
  ),
  SiteCardData(
    title: 'tailornova',
    description: 'an online fashion design tool for visualizing garments in 3D and generating custom-fitted sewing patterns',
    tags: ['design', 'tool', 'fashion'],
    url: 'https://tailornova.com/',
  ),
  SiteCardData(
    title: 'random outfit generator',
    description: 'randomly generates outfit descriptions to help writers detail what characters are wearing',
    tags: ['worldbuilding', 'writing', 'generator'],
    url: 'https://www.springhole.net/writing_roleplaying_randomators/randomoutfit.htm',
  ),
  SiteCardData(
    title: 'worldbuilding tools list',
    description: 'a curated list of tools and resources for worldbuilding',
    tags: ['worldbuilding', 'reference', 'list'],
    url: 'https://worldbuildingpasta.blogspot.com/p/tools-and-resources.html',
  ),
  SiteCardData(
    title: 'vulgar',
    description: 'a conlang generator that builds a constructed language complete with grammar and vocabulary',
    tags: ['worldbuilding', 'language', 'generator'],
    url: 'https://www.vulgarlang.com/',
  ),
  SiteCardData(
    title: 'name smasher',
    description: 'mashes two random names together to create a new one',
    tags: ['names', 'writing', 'generator'],
    url: 'https://www.springhole.net/writing_roleplaying_randomators/namesmasher.htm',
  ),
  SiteCardData(
    title: 'fantasy calendar generator',
    description: 'generates a custom fantasy calendar for worldbuilding',
    tags: ['worldbuilding', 'generator'],
    url: 'https://donjon.bin.sh/fantasy/calendar/',
  ),
  SiteCardData(
    title: 'eplans',
    description: 'look up blueprints of real houses by number of rooms and square footage',
    tags: ['worldbuilding', 'reference', 'lookup'],
    url: 'https://www.eplans.com/',
  ),
  SiteCardData(
    title: 'windows error generator',
    description: 'generates images of made-up windows error messages',
    tags: ['generator', 'image', 'novelty'],
    url: 'https://shikoshib.ru/tools/winerr',
  ),
  SiteCardData(
    title: '3d gifmaker',
    description: 'creates a spinning 360-degree gif from a photo',
    tags: ['generator', 'image', 'tool'],
    url: 'https://www.3dgifmaker.com/360Spin',
  ),
  SiteCardData(
    title: 'minecraft achievement generator',
    description: 'generates images of custom minecraft achievement popups',
    tags: ['generator', 'image', 'novelty'],
    url: 'https://skinmc.net/achievement',
  ),
  SiteCardData(
    title: 'vaporwave text generator',
    description: 'generates vaporwave-style retro text images',
    tags: ['generator', 'image', 'design'],
    url: 'https://m.photofunia.com/effects/retro-wave',
  ),
  SiteCardData(
    title: 'photopea',
    description: 'a free, open, offbrand alternative to photoshop for editing images online',
    tags: ['design', 'tool', 'image'],
    url: 'https://www.photopea.com/',
  ),
  SiteCardData(
    title: 'freesewing',
    description: 'customizes sewing patterns based on your own measurements',
    tags: ['sewing', 'design', 'tool'],
    url: 'https://freesewing.eu/',
  ),
  SiteCardData(
    title: 'color blend tool',
    description: 'blends two colors together and shows the steps in between',
    tags: ['color', 'design', 'tool'],
    url: 'https://meyerweb.com/eric/tools/color-blend/#:::hex',
  ),
  SiteCardData(
    title: 'tip of my tongue',
    description: 'helps you find a word that is on the tip of your tongue',
    tags: ['words', 'lookup'],
    url: 'https://chir.ag/projects/tip-of-my-tongue/',
  ),
  SiteCardData(
    title: 'mynoise',
    description: 'a customizable soundscape looper for background noise and relaxation',
    tags: ['audio', 'tool', 'relaxation'],
    url: 'https://mynoise.net/',
  ),
  SiteCardData(
    title: 'ipa typeit',
    description: 'an online keyboard for typing IPA (International Phonetic Alphabet) symbols',
    tags: ['language', 'tool', 'writing'],
    url: 'https://ipa.typeit.org/',
  ),
  SiteCardData(
    title: "baker's hotline",
    description: 'a hotline (including chat and email) with baking experts to help you figure out what to do when you mess up a recipe',
    tags: ['cooking', 'reference', 'tool'],
    url: 'https://www.kingarthurbaking.com/bakers-hotline',
  ),
  SiteCardData(
    title: 'compass direction calculator',
    description: 'determines the compass direction between two locations',
    tags: ['geography', 'tool', 'lookup'],
    url: 'https://planetcalc.com/7042/',
  ),
  SiteCardData(
    title: 'phoneme synthesis',
    description: 'converts an IPA transcription into synthesized speech',
    tags: ['language', 'tool', 'audio'],
    url: 'https://itinerarium.github.io/phoneme-synthesis/',
  ),
];

const libraryCards = [
  SiteCardData(
    title: 'earth',
    description: 'an interactive global weather map',
    tags: ['science', 'geography'],
    url: 'https://earth.nullschool.net/',
  ),
  SiteCardData(
    title: 'library of babel',
    description: 'a virtual replication of the fictional library of babel',
    tags: ['literature', 'myth'],
    url: 'https://libraryofbabel.info/',
  ),
  SiteCardData(
    title: 'space elevator',
    description: 'a virtual expedition from earth to outer space',
    tags: ['science', 'space'],
    url: 'https://neal.fun/space-elevator/',
  ),
  SiteCardData(
    title: 'the deep sea',
    description: 'a virtual expedition down to the bottom of the sea',
    tags: ['science', 'ocean'],
    url: 'https://neal.fun/deep-sea/',
  ),
  SiteCardData(
    title: 'size of space',
    description: 'an interactive visualization of outer space',
    tags: ['science', 'space'],
    url: 'https://neal.fun/size-of-space/',
  ),
  SiteCardData(
    title: 'radio garden',
    description: 'spin a virtual globe and tune into live radio stations from cities around the world',
    tags: ['language', 'radio', 'world'],
    url: 'https://radio.garden/',
  ),
  SiteCardData(
    title: 'same energy',
    description: 'use an image to search for other images with similar energy',
    tags: ['art', 'design', 'tool'],
    url: 'https://same.energy/',
  ),
  SiteCardData(
    title: 'random street view',
    description: 'drops you into a random street view somewhere around the world',
    tags: ['geography', 'travel'],
    url: 'https://randomstreetview.com/',
  ),
  SiteCardData(
    title: 'etymonline',
    description: 'look up a word to learn about its origins and adaptations over time',
    tags: ['language', 'history'],
    url: 'https://www.etymonline.com/',
  ),
  SiteCardData(title: 'monkeytype', description: 'a minimal, customizable typing test', tags: ['skill', 'test'], url: 'https://monkeytype.com/'),
  SiteCardData(
    title: 'ventusky',
    description: 'an animated, interactive map of global weather - wind, temperature, pressure, and more',
    tags: ['weather', 'geography'],
    url: 'https://www.ventusky.com/#p=48.5;-94.5;5',
  ),
  SiteCardData(
    title: 'mondrian and me',
    description: 'generates a unique piece of art in the style of Piet Mondrian, just for you',
    tags: ['art', 'generative', 'interactive'],
    url: 'https://mondrianandme.com/',
  ),
  SiteCardData(
    title: 'click the red button',
    description: 'a big red button that dares you to click it',
    tags: ['novelty'],
    url: 'https://clicktheredbutton.com/',
  ),
  SiteCardData(
    title: 'the useless web',
    description: 'sends you to a random, delightfully useless website every time you press the button',
    tags: ['novelty', 'random'],
    url: 'https://theuselessweb.com/',
  ),
  SiteCardData(
    title: 'onezoom',
    description: 'an interactive, zoomable tree of life showing how every species is related',
    tags: ['science', 'biology'],
    url: 'https://www.onezoom.org/',
  ),
  SiteCardData(
    title: 'worldwide telescope',
    description: 'an interactive, zoomable atlas of the night sky built from real telescope imagery',
    tags: ['science', 'space'],
    url: 'https://worldwidetelescope.org/',
  ),
  SiteCardData(
    title: 'the true size of',
    description: 'lets you drag countries around a world map to compare their real size, since flat maps distort it',
    tags: ['geography'],
    url: 'https://thetruesize.com/',
  ),
  SiteCardData(
    title: 'information is beautiful',
    description: 'a collection of striking data visualizations that turn complex topics into clear graphics',
    tags: ['data', 'design'],
    url: 'https://informationisbeautiful.net/',
  ),
  SiteCardData(
    title: 'typelit',
    description: 'a typing practice tool that has you type out passages from classic literature',
    tags: ['typing', 'literature'],
    url: 'https://www.typelit.io/',
  ),
  SiteCardData(
    title: 'keybr',
    description: 'an adaptive typing tutor that builds custom lessons to target your weak keys',
    tags: ['typing', 'skill'],
    url: 'https://www.keybr.com/',
  ),
  SiteCardData(
    title: 'line mode browser',
    description: "a recreation of the world's first website and browser, hosted at CERN where the web was born",
    tags: ['history', 'internet'],
    url: 'https://line-mode.cern.ch/www/hypertext/WWW/TheProject.html',
  ),
  SiteCardData(
    title: 'all that\'s interesting',
    description: 'a trove of offbeat articles on history, oddities, and the stranger corners of the world',
    tags: ['history', 'trivia'],
    url: 'https://allthatsinteresting.com/',
  ),
  SiteCardData(
    title: 'looper',
    description: 'entertainment and pop culture explainers on movies, TV, and celebrity news',
    tags: ['entertainment', 'movies'],
    url: 'https://www.looper.com/',
  ),
  SiteCardData(
    title: 'emoticon hub',
    description: 'a browsable library of emoticons and kaomoji ready to copy and paste',
    tags: ['novelty', 'internet culture'],
    url: 'https://emoticonhub.com/',
  ),
  SiteCardData(
    title: 'eel slap',
    description: 'lets you slap a man in the face with an eel, repeatedly, for no reason',
    tags: ['novelty', 'silly'],
    url: 'http://eelslap.com/',
  ),
  SiteCardData(
    title: 'pointer pointer',
    description: 'shows you a photo of someone pointing at wherever your cursor happens to be',
    tags: ['novelty', 'silly'],
    url: 'https://pointerpointer.com/',
  ),
  SiteCardData(
    title: 'where do i eat lmao',
    description: 'helps you decide where to eat when you just cannot decide',
    tags: ['novelty', 'food'],
    url: 'https://where-do-i-eat-lmao.vercel.app/',
  ),
  SiteCardData(
    title: 'staggering beauty',
    description: 'a wobbly, screaming worm you can fling around the screen with your mouse',
    tags: ['novelty', 'silly'],
    url: 'http://www.staggeringbeauty.com/',
  ),
  SiteCardData(
    title: 'runpee',
    description: 'tells you the best moments to step out during a movie without missing anything important',
    tags: ['movies', 'tool'],
    url: 'https://runpee.com/',
  ),
  SiteCardData(
    title: 'australian museum: animals',
    description: 'profiles of Australian wildlife with facts, photos, and identification guides',
    tags: ['science', 'animals'],
    url: 'https://australian.museum/learn/animals/',
  ),
  SiteCardData(
    title: 'reverse dictionary',
    description: 'describe the concept you mean and it finds the word you are looking for',
    tags: ['words', 'language'],
    url: 'https://reversedictionary.org/',
  ),
  SiteCardData(
    title: 'because recollection: metronomy',
    description: 'an interactive audio-visual trip through Metronomy\'s music, part of Because Music\'s 10-year anniversary project',
    tags: ['music', 'interactive'],
    url: 'http://because-recollection.com/metronomy',
  ),
  SiteCardData(
    title: 'cameron\'s world',
    description: 'a nostalgic collage of animated gifs and text excavated from archived GeoCities pages',
    tags: ['nostalgia', 'internet culture'],
    url: 'https://www.cameronsworld.net/',
  ),
  SiteCardData(
    title: 'million dollar homepage',
    description: 'a graphic time capsule of the internet in 2005, built pixel by pixel from a million purchased ad squares',
    tags: ['internet culture', 'history'],
    url: 'https://milliondollarhomepage.com/',
  ),
  SiteCardData(
    title: 'ripples',
    description: 'an interactive WebGL water simulation that ripples wherever you click and drag',
    tags: ['interactive', 'simulation'],
    url: 'https://nicopowa.github.io/ripples3/',
  ),
  SiteCardData(
    title: 'line 05x6',
    description: 'a hypnotic generative line animation from Chris Shier\'s long-running line art series',
    tags: ['generative', 'art', 'interactive'],
    url: 'https://csh.bz/line/05x6.html',
  ),
  SiteCardData(
    title: 'naming practices guide',
    description: 'a guide to naming practices and conventions in different cultures',
    tags: ['names', 'reference', 'culture'],
    url: 'https://www.fbiic.gov/public/2008/nov/Naming_practice_guide_UK_2006.pdf',
  ),
  SiteCardData(
    title: 'recommend me a book',
    description: 'shows you the first page of a random book and lets you decide whether to reveal the title and author',
    tags: ['books', 'interactive'],
    url: 'https://recommendmeabook.com/',
  ),
  SiteCardData(
    title: 'language is a virus',
    description: 'a collection of creative writing techniques and exercises',
    tags: ['writing', 'reference'],
    url: 'https://www.languageisavirus.com/creative-writing-techniques/',
  ),
  SiteCardData(
    title: 'can i play that',
    description: 'accessibility reviews of video games',
    tags: ['games', 'accessibility', 'reference'],
    url: 'https://caniplaythat.com/',
  ),
  SiteCardData(
    title: 'venn diagram of english phonemes',
    description: 'a venn diagram showing english phonemes grouped by natural class',
    tags: ['language', 'reference'],
    url: 'https://allthingslinguistic.com/post/33605639325/phonological-natural-classes-and-set-theory',
  ),
  SiteCardData(
    title: "ian's shoelace site",
    description: 'an exhaustive reference of shoelace knots and lacing methods',
    tags: ['reference', 'diy'],
    url: 'https://www.fieggen.com/shoelace/',
  ),
  SiteCardData(
    title: 'latin insults',
    description: 'a handout of insults in latin',
    tags: ['language', 'novelty', 'reference'],
    url: 'https://www.ou.edu/ludilatini/insultshandoutFall2003.htm',
  ),
  SiteCardData(
    title: 'hou tu pranownse inglish',
    description: 'a tongue-in-cheek proposal for reforming english spelling to match pronunciation',
    tags: ['language', 'novelty'],
    url: 'https://zompist.com/spell.html',
  ),
  SiteCardData(
    title: 'the food timeline',
    description: 'a historical reference tracing the origins of foods and recipes',
    tags: ['cooking', 'reference', 'history'],
    url: 'https://www.foodtimeline.org/',
  ),
  SiteCardData(
    title: 'letter frequency chart',
    description: 'a chart of letter and next-letter frequencies in english',
    tags: ['words', 'reference', 'data'],
    url: 'https://www.reddit.com/r/dataisbeautiful/comments/6rk2yr/letter_and_nextletter_frequencies_in_english_oc/#lightbox',
  ),
];

const arcadeCards = [
  SiteCardData(
    title: 'outlier',
    description: 'try to come up with the rarest word in a 5 x 5 grid of letters',
    tags: ['words', 'game'],
    url: 'https://playoutlier.com/sr/TGV2G7',
  ),
  SiteCardData(
    title: 'wayword',
    description: 'make the shortest ladders between two words',
    tags: ['words', 'game'],
    url: 'https://wayword.fun/daily',
  ),
  SiteCardData(
    title: 'dialed',
    description: "try to recreate a color you've just been shown",
    tags: ['color', 'art', 'game'],
    url: 'https://dialed.gg/',
  ),
  SiteCardData(
    title: 'animalist',
    description: "list as many animals as you can",
    tags: ['animals', 'trivia', 'game'],
    url: 'https://rose.systems/animalist/',
  ),
  SiteCardData(title: 'clozemaster', description: 'language-learning game where you fill out the word missing from a sentence', tags: ['language', 'educational', 'game'], url: 'https://www.clozemaster.com'),
  SiteCardData(title: 'the gostak', description: 'text adventure game based on the linguistic thought experiment The Gostak', tags: ['language', 'game'], url: 'https://iplayif.com/?story=https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Fzcode%2Fgostak.z5'),
  SiteCardData(
    title: 'fancy pants adventure',
    description: 'a side-scrolling platformer starring a stick-figure in fancy pants, known for its fluid running and jumping',
    tags: ['side-scroller', 'platformer', 'game', 'nostalgia'],
    url: 'https://www.newgrounds.com/portal/view/301341',
  ),
  SiteCardData(
    title: 'geotastic',
    description: 'drops you into a random Street View location and challenges you to guess where in the world you are',
    tags: ['geography', 'travel'],
    url: 'https://geotastic.net/home',
  ),
  SiteCardData(
    title: 'worldle',
    description: 'a daily guessing game where you identify a country from its silhouette',
    tags: ['geography', 'game'],
    url: 'https://worldle.teuteuf.fr/',
  ),
  SiteCardData(
    title: 'language guesser',
    description: 'plays a short music video clip and challenges you to guess what language is being spoken',
    tags: ['language', 'music'],
    url: 'https://languageguesser.com/en',
  ),
  SiteCardData(
    title: 'redactle',
    description: 'uncovers a redacted Wikipedia article one guessed word at a time until you can identify the topic',
    tags: ['words', 'history'],
    url: 'https://redactle.net/',
  ),
  SiteCardData(
    title: 'contexto',
    description: 'a daily word-guessing game that scores each guess by how semantically close it is to the secret word',
    tags: ['words', 'game'],
    url: 'https://contexto.me/',
  ),
  // No url yet - not confident in a current, correct link for this one.
  SiteCardData(
    title: 'a dark room',
    description: 'a minimalist text-based survival game that starts with just a dying fire and grows into an exploration of what lies beyond',
    tags: ['minimalist', 'survival', 'game'],
    url: 'https://adarkroom.doublespeakgames.com/',
  ),
  SiteCardData(
    title: 'level devil',
    description: 'a side-scrolling platformer that attempts to infuriate the player by throwing in tricks and traps',
    tags: ['side-scroller', 'platformer', 'game'],
    url: 'https://leveldevilfull.com/',
  ),
  SiteCardData(
    title: 'idea games',
    description: 'a collection of mini games',
    tags: ['novelty', 'game'],
    url: 'https://www.ideagames.fun/',
  ),
  SiteCardData(
    title: 'anthropeum',
    description: 'ranked competition game where you are shown an artifact and have to guess its origin',
    tags: ['history', 'archaeology', 'game'],
    url: 'https://anthropeum.com/',
  ),
  SiteCardData(
    title: 'zanagrams',
    description: 'a daily word game where you connect letters to create words',
    tags: ['words', 'puzzle', 'game'],
    url: 'https://zanagrams.com/',
  ),
  SiteCardData(
    title: 'sandboxels',
    description: 'a falling-sand physics sandbox with hundreds of elements that react, burn, and combine',
    tags: ['sandbox', 'simulation', 'creativity'],
    url: 'https://neal.fun/sandboxels/',
  ),
  SiteCardData(
    title: 'cook',
    description: 'a sandbox for chopping, mixing, and cooking up whatever dish you can imagine',
    tags: ['sandbox', 'cooking'],
    url: 'https://r74n.com/cook/',
  ),
  SiteCardData(
    title: 'zen garden',
    description: 'a relaxing digital zen garden you can rake and rearrange with your cursor',
    tags: ['relaxation', 'sandbox', 'simulation', 'creative'],
    url: 'https://paint.toys/zen-garden/',
  ),
  SiteCardData(
    title: 'particle garden',
    description: 'a falling-particle sandbox where you paint with elements and watch them react and interact',
    tags: ['sandbox', 'simulation', 'creative'],
    url: 'https://www.particlegarden.com/',
  ),
];

const allSiteCards = [...studioCards, ...libraryCards, ...arcadeCards];
